name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt-get install wget build-essential python3 python3-setuptools python3-pytest

      - name: Create Python virtual environment
        run: |
          python3 -m venv --system-site-packages .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
          echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH
        shell: bash

      # Install (n)Migen / LiteX / Cores
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py init install --config=minimal

      # Install Project
      - name: Install Project
        run: |
          python3 -m pip install --editable .

      # Test
      - name: Run Tests
        run: |
          python3 -m pytest -v
